export const experienceData = [
  {
    role: "Graduate Grader - CASCS 599: Advanced Topics in Computer Vision",
    year: "Sep'25 - Present",
    description: [
      "Grader for CASCS 599: Advanced Topics in Computer Vision under Prof. Deepti Ghadiyaram, evaluating graduate projects in computer vision, generative AI, and multimodal learning.",
      "Mentored students on research design, experimentation, and reproducibility, helping refine model evaluation and reporting.",
      "Contributed to rubric design and feedback systems, improving the clarity and consistency of technical evaluations.",
    ],
    company: "Boston University",
    companyColor: "#FFFFFF",
    companyOutlineColor: "#7C3AED",
    technologies: [
      "Code Evaluation",
      "Student Mentorship",
      "Technical Feedback",
      "Debugging Guidance",
    ],
    url: "https://docs.google.com/document/u/5/d/e/2PACX-1vSiLhPTTrSwnJKsfEQBB5QfnJV__sYH1iMlDXggRxgKzQb-TvTneWEX0JrFZhjFE8va7ZZbhgT0emWX/pub?pli=1",
  },
  {
    role: "Graduate Researcher",
    year: "Oct'24 - Present",
    description: [
      "Conducting applied research in AI, generative modeling, and multimodal learning, integrating vision, language, and audio modalities.",
      "Created an agentic parental-control web app using LangGraph for intelligent screen monitoring and behavior prediction.",
      "Designed music generation frameworks combining Transformer, Diffusion, and Mamba SSM architectures to enhance fidelity and semantic alignment.",
      "Adapted the open-source project Vision-Language-For-The-Blind to create a vision–language question answering system combining image captioning, question generation, and accessibility-focused reasoning.",
      "Developed a sign language translation system using DenseNet + LSTM for real-time gesture-to-text communication, trained on the WLASL dataset.",
      "Built a cancer detection pipeline using CNN-based histopathology image analysis to classify tumor subtypes and support early screening workflows.",
      "Authored technical documentations, contributing to the academic research community.",
    ],
    company: "Boston University",
    companyColor: "#FFFFFF",
    companyOutlineColor: "#7C3AED",
    technologies: [
      "PyTorch",
      "LangChain",
      "Transformers",
      "LLMs",
      "Computer Vision",
      "NLP",
      "Generative AI",
      "FastAPI",
      "React",
      "LangGraph",
      "SQL",
    ],
    url: "https://www.bu.edu/",
  },
  {
    role: "Software Developer I",
    year: "Aug'22' - Nov'23",
    description: [
      "Led a 3-person R&D team developing and integrating machine learning features into Oracle’s forecasting and analytics tools, improving accuracy and decision speed for enterprise clients.",
      "Built Java-based automation frameworks that streamlined testing and release processes, saving 3–5 developer-days per sprint and ensuring faster, more reliable deployments.",
      "Designed and deployed data analytics engines within financial and supply chain modules to deliver real-time trend detection, reduce reporting errors, and enhance insight quality across large datasets.",
      "Collaborated closely with DevOps, Cloud, and Data Engineering teams to ensure high system uptime, better performance visibility, and smoother end-to-end product releases.",
    ],
    company: "Oracle",
    companyColor: "#FFFFFF",
    companyOutlineColor: "#7C3AED",
    technologies: [
      "Java",
      "Python",
      "Machine Learning",
      "Data Analytics",
      "OCI",
      "SQL",
      "Automation",
      "CI/CD",
    ],  
    url: "https://www.oracle.com/",
  },
  {
    role: "Software Developer Intern",
    year: "Jan'22' - Jul'23",
    description: [
      "Built the foundation for ML-driven analytics systems, focusing on early-stage models that monitored performance metrics and predicted system bottlenecks.",
      "Developed a distributed monitoring setup using Zipkin, Prometheus, and Java EE, enabling real-time tracing and faster detection of issues across multiple services.",
      "Designed and tested REST APIs and backend modules for Oracle Cloud applications, improving reliability, scalability, and integration efficiency.",
      "Partnered with senior developers to automate performance reporting and strengthen observability across production environments.",
    ],
    company: "Oracle",
    companyColor: "#FFFFFF",
    companyOutlineColor: "#7C3AED",
    technologies: [
      "Java",
      "Machine Learning",
      "Prometheus",
      "Zipkin",
      "OCI",
      "SQL",
      "Docker",
      "CI/CD",
    ],
    url: "https://www.oracle.com/",
  },
];
