export const resumeKeywords = [
  // Personal Branding & Roles
  "Gagan Singhal",
  "Gagan Singhal resume",
  "Gagan Singhal portfolio",
  "Gagan Singhal AI Engineer",
  "Gagan Singhal Boston University",
  "Gagan Singhal generative AI",
  "Gagan Singhal machine learning engineer",
  "AI Engineer Boston",
  "AI Engineer Boston MA",
  "Machine Learning Engineer Boston",
  "Generative AI Engineer",
  "Multimodal AI Researcher",
  "AI Researcher Boston University",
  "Graduate Researcher Boston University",
  "Oracle Software Developer",
  "Full Stack AI Developer",
  "AI Solutions Engineer",
  "Agentic AI Engineer",
  "Remote AI Engineer",
  "Boston-based AI talent",
  "US-based AI engineer",
  "STEM OPT eligible engineer",
  "AI Engineer United States",
  "Generative AI Specialist",
  "Applied AI Engineer",
  "AI Product Engineer",
  "AI Platform Engineer",
  "AI Research Engineer",
  "AI Solutions Architect",
  "Full Stack Machine Learning Engineer",
  "Data Scientist Boston",
  "AI Consultant",
  "AI Innovation Lead",
  "AI Prototyper",
  "Edge AI Engineer",
  "AI Ethics Champion",

  // Core Technical Strengths
  "Generative AI Systems",
  "Agentic AI Systems",
  "Agent workflows",
  "LLM Applications",
  "Large Language Models",
  "Transformer Models",
  "Diffusion Models",
  "Mamba SSM",
  "Multimodal Learning",
  "Vision Language Models",
  "Computer Vision Engineer",
  "Natural Language Processing",
  "Edge AI",
  "On-device AI",
  "AI Safety",
  "Responsible AI",
  "Human centered AI",
  "Explainable AI",
  "RAG Architectures",
  "Retrieval augmented generation",
  "LLM Guardrails",
  "LLM Evaluation",
  "LLM Fine Tuning",
  "Prompt Orchestration",
  "Self-supervised Learning",
  "Few-shot Learning",
  "Contrastive Learning",
  "Reinforcement Learning",
  "Time Series Forecasting",
  "Anomaly Detection",

  // Signature Skills & Tools
  "LangGraph",
  "LangGraph Developer",
  "LangGraph pipelines",
  "LangChain",
  "Prompt Engineering",
  "PyTorch",
  "Python",
  "Torchvision",
  "Lightning Fabric",
  "FastAPI",
  "Streamlit",
  "Next.js",
  "React",
  "TypeScript",
  "Node.js",
  "Node.js microservices",
  "RESTful APIs",
  "GraphQL APIs",
  "API Security",
  "PostgreSQL",
  "pgvector",
  "Vector databases",
  "SQLCipher",
  "MongoDB",
  "Supabase",
  "Neo4j",
  "Redis",
  "Data Pipelines",
  "ETL Pipelines",
  "Data Orchestration",
  "Airflow",
  "Prefect",
  "CI/CD Automation",
  "GitHub Actions",
  "GitOps",
  "Docker",
  "Vercel",
  "AWS",
  "AWS Lambda",
  "AWS S3",
  "Cloudflare Workers",
  "Cloud Deployment",
  "Observability Engineering",
  "Zipkin",
  "Prometheus",
  "Grafana",
  "OpenTelemetry",
  "Java",
  "Automation Frameworks",
  "JUnit Testing",
  "Selenium Automation",
  "Playwright End-to-End Testing",
  "LangGraph Agents",
  "Ollama",
  "OpenAI API",
  "Anthropic Claude",
  "Google Gemini",
  "Hugging Face Models",
  "Supabase Edge Functions",
  "Serverless AI",
  "MLOps",
  "Experiment Tracking",
  "Weights and Biases",
  "Model Deployment",
  "Model Monitoring",
  "Inference Optimization",
  "ONNX Runtime",
  "TensorRT",
  "Real-time Inference",
  "Edge Deployment",
  "Security Compliance",

  // Project Highlights & Focus Areas
  "WatchIt parental control AI",
  "On-device screen moderation",
  "Realtime safety guardrails",
  "MBTA transit analytics",
  "Transit demand forecasting",
  "ListIt collaborative productivity app",
  "The Assistant Chrome extension",
  "VendIt multi-agent simulator",
  "Autonomous agent coordination",
  "Generative music model AlphaBeat",
  "Music diffusion model",
  "Sign language translation AI",
  "Vision Language For The Blind adaptation",
  "LangGraph parental control agent",
  "Cancer detection pipeline",
  "AI for accessibility",
  "AI for safety",
  "Predictive analytics solutions",
  "Enterprise automation",
  "Intelligent monitoring systems",
  "Data-driven decision support",
  "Generative UI prototypes",
  "LLM powered knowledge base",
  "Interactive AI dashboards",
  "Autonomous safety agents",
  "AI powered parental controls",
  "Urban mobility analytics",
  "Healthcare diagnostics AI",
  "Assistive communication technology",
  "AI-driven creative tools",
  "Generative audio systems",

  // Employer & Location Signals
  "Boston MA",
  "Massachusetts tech talent",
  "United States work authorization",
  "Boston University innovation",
  "Oracle Cloud Infrastructure experience",
  "Enterprise SaaS R&D",
  "Enterprise forecasting tools",
  "Boston tech ecosystem",
  "Massachusetts startup scene",
  "Boston University AI research",
  "CASCS 599 teaching assistant",
  "Boston innovation labs",
  "Oracle India Development Centre",

  // Career Intent
  "Open to full-time AI roles",
  "Open to AI research roles",
  "Open to applied AI roles",
  "AI product prototyping",
  "Research to production AI",
  "Cross-functional collaboration",
  "Technical mentorship",
  "Human centered AI design",
  "AI team leadership",
  "Innovation initiatives",
  "Data informed decision making",
  "Rapid prototyping",
  "Cross-disciplinary collaboration",
  "Product discovery workshops",
  "Stakeholder alignment",
  "AI product lifecycle",

  // Research & Academic Interests
  "Computer vision research",
  "Multimodal research",
  "Generative model evaluation",
  "Agent benchmarking",
  "Graduate teaching assistant",
  "Academic research support",
  "Peer code review",
  "Research reproducibility",
  "Scientific writing",
  "Conference submissions",
  "AI literature review",
  "Experiment design",

  // Community & Outreach
  "AI mentorship",
  "Hackathon mentor",
  "Technical blogging",
  "Speaker on AI",
  "Open source AI contributor",
  "AI ethics advocate",
  "Accessible AI solutions",
  "STEM outreach",
  "AI community builder",
  "Developer evangelism",
  "AI workshop facilitator",
  "Tech conference speaker",
  "AI newsletter author",
  "Student mentorship",
  "Women in AI ally",
];
