export const selfData = {
  name: "Aarab Nishchal",
  first_name: "Aarab",
  last_name: "Nishchal",
  jobTitle: "Student Developer",
  workFor: "KIIT University",
  current_location: {
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
  },
  DOB: {
    dd: 9,
    mm: 8,
    yyyy: 2004,
  },
  email: "aarab.nishchal@gmail.com",
  roles: [
    "Chief Problem Solver",
    "Idea Mechanic",
    "Possibility Pilot",
    "Chaos Coordinator",
    "Chief Tinkerer",
    "Glitch Gladiator",
    "Solution Sorcerer",
    "Joyful Juggler",
  ],
  desc: "I design and build tools that live on the internet.",
  bio: "I'm a student developer passionate about crafting digital experiences. I love building intuitive web apps, exploring new technologies, and turning creative ideas into accessible tools.",
  about: [
    "Hi, I'm a student developer who likes breaking things just to figure out how to fix them usually with JavaScript and snacks. I build web apps that try their best to work on the first try (no promises though).",
    "React and Tailwind are my daily tools, and I'm currently exploring the mysterious land of backend development where bugs go to multiply. Full-stack dreams, coffee-fueled nights, and lots of console.log.",
    "When I'm not coding, I'm either daydreaming startup ideas, lurking on GitHub, or explaining to my friends why 'it works on my machine' is totally valid. I love creating stuff that’s fun, functional, and maybe a little chaotic.",
  ],

  socials_username: {
    facebook: "zzcwc",
    github: "aarabii",
    instagram: "aarab.ii",
    leetcode: "aarabii",
    linkedin: "aarab-nishchal",
    snapchat: "aarab.ii",
    telegram: "aarab_ii",
    twitter: "aarab_ii",
  },
};
